server:
  port: 10001

spring:
  datasource:
    url: jdbc:mysql://122.51.2.197:3306/muxin
    username: chimm
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 分页设置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

############################################################
#
# 分布式文件系统 fastdfs 配置
#
############################################################
fdfs:
  soTimeout: 1501
  connectTimeout: 601
  thumbImage.width: 80
  thumbImage.height: 80
  trackerList[0]: 122.51.2.197:22122