centsos:
  ip: 172.16.120.139

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${centsos.ip}:3306/demo01
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
